# Generated by Django 5.2.1 on 2025-06-19 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Категория",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("название", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Объявление",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("заголовок", models.CharField(max_length=255)),
                ("контакты", models.CharField(blank=True, max_length=255, null=True)),
                ("регион", models.CharField(blank=True, max_length=255, null=True)),
                ("описание", models.TextField(blank=True, default="", null=True)),
                ("дата_создания", models.DateTimeField(auto_now_add=True)),
                (
                    "изображение",
                    models.ImageField(blank=True, null=True, upload_to="ads_images/"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "категория",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="board.категория",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Комментарий",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("текст", models.TextField(verbose_name="Комментарий")),
                ("дата_создания", models.DateTimeField(auto_now_add=True)),
                (
                    "пользователь",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "объявление",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="комментарии",
                        to="board.объявление",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ГидДетали",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("возраст", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "тип_путешествия",
                    models.CharField(
                        choices=[
                            ("Пеший", "Пеший"),
                            ("Лыжный", "Лыжный"),
                            ("Водный", "Водный"),
                            ("Горный", "Горный"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "опыт",
                    models.CharField(
                        blank=True,
                        help_text="Опыт руководства (например, «5 лет»)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "объявление",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="гид_детали",
                        to="board.объявление",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ПоходДетали",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "дата_начала",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "длина_маршрута",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "сложность",
                    models.CharField(
                        choices=[
                            ("Легко", "Легко"),
                            ("Средне", "Средне"),
                            ("Сложно", "Сложно"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "тип_путешествия",
                    models.CharField(
                        choices=[
                            ("Пеший", "Пеший"),
                            ("Лыжный", "Лыжный"),
                            ("Водный", "Водный"),
                            ("Горный", "Горный"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "размер_группы",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("требования", models.TextField(blank=True, null=True)),
                ("руководитель", models.CharField(max_length=100)),
                (
                    "стоимость",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "объявление",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="поход_детали",
                        to="board.объявление",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="СнаряжениеДетали",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "вес",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "объявление",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="снаряжение_детали",
                        to="board.объявление",
                    ),
                ),
            ],
        ),
    ]
