# Generated by Django 5.2.1 on 2025-06-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="походдетали",
            name="сложность",
            field=models.CharField(
                choices=[
                    ("1 к.с.", "1 к.с."),
                    ("2 к.с.", "2 к.с."),
                    ("3 к.с.", "3 к.с."),
                    ("4 к.с.", "4 к.с."),
                    ("5 к.с.", "5 к.с."),
                    ("6 к.с.", "6 к.с."),
                    ("ПВД", "ПВД"),
                ],
                max_length=50,
            ),
        ),
    ]
