# Generated by Django 5.2.1 on 2025-06-21 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_alter_походдетали_сложность"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="объявление",
            name="избранное",
            field=models.ManyToManyField(
                blank=True,
                db_table="board_объявление_избранное_v2",
                related_name="favorite_ads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
