# Generated by Django 5.2.1 on 2025-06-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_объявление_просмотры"),
    ]

    operations = [
        migrations.AddField(
            model_name="объявление",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Актуально"),
        ),
    ]
