# Generated by Django 5.2.1 on 2025-06-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_объявление_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="снаряжениедетали",
            name="стоимость",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
