# Generated by Django 5.2.1 on 2025-06-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_снаряжениедетали_стоимость"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("изображение_url", models.URLField()),
            ],
        ),
    ]
